services:
  envoy:
    image: envoyproxy/envoy:v1.33-latest
    env_file:
      - .env
    entrypoint: ["/bin/sh", "/docker-entrypoint-envoy.sh"]
    volumes:
      - ./envoy.yaml.template:/etc/envoy/envoy.yaml.template:ro
      - ./docker-entrypoint-envoy.sh:/docker-entrypoint-envoy.sh:ro
    ports:
      - "10000:10000"
      - "9901:9901"
    depends_on:
      - delayed_service

  delayed_service:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "3000:3000"
